### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by paulvill** [cdanewschool/vr_embryo#7]
# Roadmap

### Project Background
Datasets of embryogenesis are 3D+time image datasets with multiple modalities. These datasets are notoriously complex to visualize and can be challenging to understand without a good spatial understanding of the multiple dimensions involved. There is a need to improve the ways in which researchers and the public interact with these datasets. This project will extend The Embryo Digital Atlas, an open-source web-based platform for the visualization of complex experimental datasets related to embryogenesis, through development of an open-source library in javascript to interface microscopy images of embryonic development with a Virtual Reality headset.

### Mission Statement: 

Interfacing multimodal microscopy images of developing embryos with a VR headset using the a-frame framework

### Short Term

- [ ] advance the visualization engine - basic interaction
    - [x] move through time points 
    - [ ] select / toggle channels
    - [ ] interactions with the handles

- [ ] think of innovative interaction features 
      - scrolling coolness
      - all the time points on a ring around the camera
      - comparison mechanisms: across time / modalities / species

- [ ] establish a good file system

- [ ] set up a deployment workflow

### Medium Term
- [ ] integrate the a-frame visualization to the [main website](http://www.embryodigitalatlas.org)
- [ ] incorporate embedded instructions: tooltips, guides, indicators, etc.

### Long Term
- [ ] tagging system
- [ ] navigate the website in the VR headset
